controllers:
    resource: '../src/Controller/'
    type: attribute

# program_show:
#     path: '/program/{slug}'
#     controller: 'App\Controller\ProgramController::show'
    # methods: GET
    # requirements:
    #     id: '\d+'